// <auto-generated />
namespace EmployeeAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatemodelclassnameconventions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemodelclassnameconventions));
        
        string IMigrationMetadata.Id
        {
            get { return "201811170547367_update-model-class-name-conventions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
